/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.20")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // need Clikt for parsing command line
    implementation("com.github.ajalt:clikt:1.6.+")

    // Jackson for parsing
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.9.+")
    // Need xml support to parse metadata-files and poms
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.+")

    // HTTP support
    implementation("org.jsoup:jsoup:1.11.+")

    // Log4j for logging
    implementation("org.apache.logging.log4j:log4j-api-kotlin:1.0.0")
    implementation("org.apache.logging.log4j:log4j-core:2.11.1")

    // Kafka for sending messages
    implementation("org.apache.kafka:kafka-clients:2.1.+")

    //OKHttp for performing requests
    implementation("com.squareup.okhttp3:okhttp:3.13.1")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
}

application {
    // Define the main class for the application.
    mainClassName = "com.chriswk.Scanner"
}
