/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.chriswk

import com.chriswk.mavenindexer.RepoScanner
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import org.apache.logging.log4j.kotlin.Logging

class Scanner : CliktCommand(), Logging {
    val repoUrl: String by option(help = "Repo url to scan").default("http://repo1.maven.org/maven2/")
    val kafka: String by option(help = "URL to kafka servers").default("kafka:9092")
    override fun run() {
        logger.info("going to scan $repoUrl sending coordinates to $kafka")
        RepoScanner(rootUrl = repoUrl, kafkaUrl = kafka).start()
    }
}

fun main(args: Array<String>) {
    Scanner().main(args)
}
